[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nestor-server"
version = "0.1.0"
description = "Nestor Mobile App Build"
dependencies = [
    "flet>=0.26.0",
]

[tool.flet]
name = "NestorApp"
org = "com.nestorserver"

[tool.flet.android]
version_code = 1
version_name = "1.0.0"
